-- AlterTable
ALTER TABLE "Post" ADD COLUMN     "creareAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "creareAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
